#version 460
#extension GL_EXT_debug_printf : enable

#extension GL_GOOGLE_include_directive : enable
// #include "Data_struct.h"
// layout(local_size_x = 1024) in;
layout(binding = 0) uniform Test
{
    int a;
    int b;
};
layout(set = 0, binding = 1, rgba32f) uniform image2D image;
void main()
{
    // gl_LocalInvocationID.x
    // debugPrintfEXT("message %u %u %u | %u |\n",
    //                //    gl_LocalInvocationID.x,

    //                //    gl_LocalInvocationID.y,
    //                //    gl_LocalInvocationID.z,

    //                gl_GlobalInvocationID.x,
    //                gl_GlobalInvocationID.y,
    //                gl_GlobalInvocationID.z,
    //                gl_WorkGroupID);

    // vec4 old_color = imageLoad(image, ivec2(100, 100));
    imageStore(image, ivec2(100), vec4(0.77, 0.77, 0.77, 0.77));

    if (gl_GlobalInvocationID.x == 1) {
        for (int i = 0; i < 1e3; i++) {
            float d = exp(12313.123);
            float d1 = exp(d);
            float d2 = exp(d1);

            float d3 = exp(d2);
        }
        // debugPrintfEXT("message from compute %f %f %f \n", old_color.x, old_color.y, old_color.z);
        imageStore(image, ivec2(100), vec4(0.66, 0.66, 0.66, 0.66));
    }

    // old_color.x = 0;
}